Fix remove class in body
Memcrab/react-pure-modal pull request #85
Opened 2023-06-28 17:03 UTC by VadymBezsmertnyi

Added dependencies for class removing during 'isOpen' prop changes

2023-06-29 15:37 UTC, max-mykhailenko requested changes

2023-06-29 15:37 UTC, max-mykhailenko commented on src/react-pure-modal.tsx
> +  const isClassBody = useMemo(() => document.body.classList.contains('body-modal-fix'), [isOpen]);
bad idea, you will have expensive layout on each re-render

2023-06-29 15:37 UTC, max-mykhailenko commented on src/react-pure-modal.tsx
> +      removeClassBody();
No, you already have it in function `unsetModalContext` so just check why that function doesn't run when you close the modal

2023-06-30 12:37 UTC, VadymBezsmertnyi commented on src/react-pure-modal.tsx
> +  const isClassBody = useMemo(() => document.body.classList.contains('body-modal-fix'), [isOpen]);
Agreed, I've fixed it.

2023-06-30 12:39 UTC, VadymBezsmertnyi commented on src/react-pure-modal.tsx
> +      removeClassBody();
Correct, but it is not triggered in the code when isOpen changes, so we will invoke it through the effect.

2023-06-30 12:40 UTC, max-mykhailenko commented on src/react-pure-modal.tsx
> +    document.body.classList.remove('body-modal-fix');
тобто було гарно одною функцією, а стало тепер інлайново в двох місцях?

2023-06-30 12:41 UTC, max-mykhailenko commented on src/react-pure-modal.tsx
> +    } else if (document.body.classList.contains('body-modal-fix')) {
Тут проблема, що isClassBody має неправильне значення?

2023-06-30 12:44 UTC, VadymBezsmertnyi commented on src/react-pure-modal.tsx
> +    document.body.classList.remove('body-modal-fix');
Згоден, не вірно зрозумів спочатку.

2023-06-30 12:45 UTC, VadymBezsmertnyi commented on src/react-pure-modal.tsx
> +    } else if (document.body.classList.contains('body-modal-fix')) {
Зрозумів, що useMemo може зробити не вірно при перерендерах кожного разу тай лишні перестворення функції.

2023-06-30 13:13 UTC, VadymBezsmertnyi commented
Скоротив до простого і зрозумілого функціоналу.

2023-07-01 18:07 UTC, max-mykhailenko commented on src/react-pure-modal.tsx
> +      unsetModalContext();
check if you can call `close` function

2023-07-04 17:20 UTC, VadymBezsmertnyi commented on src/react-pure-modal.tsx
> +      unsetModalContext();
You're right, the code does look more logical.

2023-07-05 07:23 UTC, max-mykhailenko approved these changes

2023-07-05 07:23 UTC, merged